### ISSUE TITLE
default readme in BIDS dataset

### ISSUE THREAD

**Issue by Remi-Gau** [wulms/bidsconvertr#1]
hey

We (BIDS maintainers) are trying to see if we can improve the quality of the average README in BIDS dataset. Those tend to be pretty thin and are missing some information we would like to see there even if it can be formalized "yet" into the BIDS specification.

Hoping to leverage the bids converters to help to do.

So I am going around the different BIDS converters repo to see if we can start improving the  default README they put in a the BIDS dataset.

There is template that is provided in the BIDS starter kit: https://github.com/bids-standard/bids-starter-kit/blob/main/templates/README.MD

Some possible options:
1. use this template is
2. use a subset of it
3. add a link to the template README
4. something else (a mix of 2 and 3?)

What do you think? I can try to open a PR if you want.

Also let us know if you think that the template README in the starter kit could / should be improved .

**Comment by wulms** [comment]
Hey Remi,

Thank you for your interest in a further standardization of BIDSconvertR.

The converter creates a README based on a template:
https://github.com/wulms/bidsconvertr/blob/master/R/metadata.R (94-114)

This can be easily edited in accordance with a standard README :)

I am totally fine changing it to the provided template!

**Comment by wulms** [comment]
Hey Remi, 
I implemented your request in https://github.com/wulms/bidsconvertr/commit/776cdf927c3f240836992913d8cb3471efa92f70
The README now is automatically downloaded from GitHub to the BIDS folder.

Let me know, if I can be of further help or if somebody from the BIDS team has interest in trying out the new version of my tool :)
